import Head from 'next/head'
import { Inter } from '@next/font/google'
import Header from '../components/Header'
import Navbar from '../components/Navbar'
import Results from '../components/Results'
import request from '../utils/request'

const inter = Inter({ subsets: ['latin'] })

export default function Home({results}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header */}
      <Header></Header>
      {/* Nav */}
      <Navbar></Navbar>
      {/* Results */}
      <Results results={results}></Results>
    </>
  )
}


export async function getServerSideProps(context){
  const genre = context.query.genre || "fetchTrending";
  const req =  await fetch(`https://api.themoviedb.org/3${request[genre].url}`).then(response=> response.json());
  return{
    props:{
      results: req.results,
    }
  }
}
